#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use BladeUI\Icons\Console\GenerateCommandBuilder;

GenerateCommandBuilder::create('blade-boxicons')
    ->fromNpmPackage('boxicons') // Optionally specify an `npm` package to load from
    ->fromSourceSvgDirectory('/svg') // Specify a directory, if an npm package isn't set, this can be anywhere
    ->withIconSets([
        'regular' => 'bx-',
        'logos' => 'bxl-',
        'solid' => 'bxs-',
    ])
    ->withSvgNormalisation(function (string $tempFilepath, string $iconSet) {
        $doc = new DOMDocument();
        $doc->load($tempFilepath);
        /**
         * @var DOMElement $svgElement
         */
        $svgElement = $doc->getElementsByTagName('svg')[0];
        $svgElement->removeAttribute('width');
        $svgElement->removeAttribute('height');
        $svgElement->removeAttribute('viewBox');
        $svgElement->setAttribute('fill', 'currentColor');
        $svgElement->setAttribute('stroke', 'none');
        $svgElement->setAttribute('viewBox', '0 0 24 24');
        $doc->save($tempFilepath);

        $svgLine = trim(file($tempFilepath)[1]);
        file_put_contents($tempFilepath, $svgLine);
    })
    ->run();